// AUTO-GENERATED by .design-sync barrel generator — do not edit by hand.
// DS bundle entry: the curated set of storied Mux components (real export
// names) + the providers the isolated-preview harness needs. Exposes them on
// window.Mux for the design agent and seeds the converter's `exported` set.
// Run `node .design-sync/gen-barrel.mjs` after stories change; it also prints
// the titleMap to merge into config.json.

export { CoderWorkspaceForm } from "@/browser/features/Runtime/CoderControls";
export { CompactingMessageContent } from "@/browser/features/Messages/CompactingMessageContent";
export { ContextSwitchWarning } from "@/browser/components/ContextSwitchWarning/ContextSwitchWarning";
export { ContextUsageIndicatorButton } from "@/browser/components/ContextUsageIndicatorButton/ContextUsageIndicatorButton";
export { DebugLlmRequestModal } from "@/browser/components/DebugLlmRequestModal/DebugLlmRequestModal";
export { DevToolsStepCard } from "@/browser/features/RightSidebar/DevToolsTab/DevToolsStepCard";
export { GeneralSection } from "@/browser/features/Settings/Sections/GeneralSection";
export { GetGoalToolCall } from "@/browser/features/Tools/GetGoalToolCall";
export { GoalTab } from "@/browser/features/RightSidebar/GoalTab";
export { HookOutputDisplay } from "@/browser/features/Tools/Shared/HookOutputDisplay";
export { InitMessage } from "@/browser/features/Messages/InitMessage";
export { InterruptedBarrier } from "@/browser/features/Messages/ChatBarrier/InterruptedBarrier";
export { KeybindsSection } from "@/browser/features/Settings/Sections/KeybindsSection";
export { MCPSettingsSection } from "@/browser/features/Settings/Sections/MCPSettingsSection";
export { MemorySection } from "@/browser/features/Settings/Sections/MemorySection";
export { PRLinkBadge } from "@/browser/components/PRLinkBadge/PRLinkBadge";
export { ProjectCreateModal } from "@/browser/components/ProjectCreateModal/ProjectCreateModal";
export { RosettaBanner } from "@/browser/components/RosettaBanner/RosettaBanner";
export { SecretsSection } from "@/browser/features/Settings/Sections/SecretsSection";
export { SecuritySection } from "@/browser/features/Settings/Sections/SecuritySection";
export { ServerAccessSection } from "@/browser/features/Settings/Sections/ServerAccessSection";
export { StreamingBarrierView } from "@/browser/features/Messages/ChatBarrier/StreamingBarrierView";
export { TitleBar } from "@/browser/components/TitleBar/TitleBar";
export { TodoToolCall } from "@/browser/features/Tools/TodoToolCall";
export { TranscriptHydrationSkeleton } from "@/browser/components/ChatPane/TranscriptHydrationSkeleton";

// ── Providers ──
export { ThemeProvider } from "@/browser/contexts/ThemeContext";
export { TooltipProvider } from "@/browser/components/Tooltip/Tooltip";
export { APIProvider } from "@/browser/contexts/API";
export { PolicyProvider } from "@/browser/contexts/PolicyContext";
export { ExperimentsProvider } from "@/browser/contexts/ExperimentsContext";
export { SettingsProvider } from "@/browser/contexts/SettingsContext";
export { RouterProvider } from "@/browser/contexts/RouterContext";
export { ProjectProvider } from "@/browser/contexts/ProjectContext";
export { AboutDialogProvider } from "@/browser/contexts/AboutDialogContext";
