name: "Setup Mux"
description: "Setup Bun and install dependencies with caching"
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Get Bun version
      id: bun-version
      shell: bash
      run: echo "version=$(bun --version)" >> $GITHUB_OUTPUT

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-bun-${{ steps.bun-version.outputs.version }}-node-modules-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-bun-${{ steps.bun-version.outputs.version }}-node-modules-

    - name: Check if node_modules exists
      id: check-node-modules
      shell: bash
      run: |
        if [ -d "node_modules" ] && [ -d "node_modules/.bin" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    # Only restore bun install cache when node_modules is completely missing.
    # This avoids 88+ seconds of tar/zstd decompression on Windows for partial cache hits.
    - name: Cache bun install cache
      if: steps.check-node-modules.outputs.exists != 'true'
      id: cache-bun-install
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-cache-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-cache-

    - name: Install dependencies
      if: steps.check-node-modules.outputs.exists != 'true'
      shell: bash
      run: bun install --frozen-lockfile

    # Cache Electron binaries and electron-builder resources (NSIS, etc.)
    # These are downloaded during electron-builder and can be 200MB+ total
    - name: Cache Electron
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/electron
          ~/Library/Caches/electron
          ~/AppData/Local/electron/Cache
        key: ${{ runner.os }}-${{ runner.arch }}-electron-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-electron-

    - name: Cache electron-builder
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/electron-builder
          ~/Library/Caches/electron-builder
          ~/AppData/Local/electron-builder/Cache
        key: ${{ runner.os }}-${{ runner.arch }}-electron-builder-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-electron-builder-
