import type { JSX } from "react";
import { useState, useEffect } from "react";
import {
  Modal,
  View,
  TextInput,
  TouchableOpacity,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
  ScrollView,
} from "react-native";
import { Picker } from "@react-native-picker/picker";
import { useTheme } from "../theme";
import { ThemedText } from "./ThemedText";
import {
  RUNTIME_MODE,
  type RuntimeMode,
  buildRuntimeString,
  parseRuntimeModeAndHost,
} from "@shared/types/runtime";
import { loadRuntimePreference } from "../utils/workspacePreferences";
import type { FrontendWorkspaceMetadata } from "../types";

interface FirstMessageModalProps {
  visible: boolean;
  projectPath: string;
  projectName: string;
  branches: string[];
  defaultTrunk?: string;
  loadError?: string | null;
  onClose: () => void;
  onSendFirstMessage: (
    message: string,
    trunkBranch: string,
    runtime?: string
  ) => Promise<FrontendWorkspaceMetadata | null>;
}

/**
 * FirstMessageModal - Mobile equivalent of desktop's FirstMessageInput
 * Allows users to create a workspace by typing their first message
 * The workspace name and branch are generated by AI based on the message content
 */
export function FirstMessageModal({
  visible,
  projectPath,
  projectName,
  branches,
  defaultTrunk,
  loadError,
  onClose,
  onSendFirstMessage,
}: FirstMessageModalProps): JSX.Element {
  const theme = useTheme();
  const spacing = theme.spacing;

  const [message, setMessage] = useState("");
  const [trunkBranch, setTrunkBranch] = useState(defaultTrunk ?? branches[0] ?? "");
  const [runtimeMode, setRuntimeMode] = useState<RuntimeMode>(RUNTIME_MODE.LOCAL);
  const [sshHost, setSshHost] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const hasBranches = branches.length > 0;

  // Update trunk branch when branches or defaultTrunk change
  useEffect(() => {
    const fallbackTrunk = defaultTrunk ?? branches[0] ?? "";
    setTrunkBranch((current) => {
      const trimmedCurrent = current.trim();

      if (!hasBranches) {
        return trimmedCurrent.length === 0 ? fallbackTrunk : current;
      }

      if (trimmedCurrent.length === 0 || !branches.includes(trimmedCurrent)) {
        return fallbackTrunk;
      }

      return current;
    });
  }, [branches, defaultTrunk, hasBranches]);

  // Update error when loadError changes
  useEffect(() => {
    setError(loadError ?? null);
  }, [loadError]);

  // Reset form when modal opens and load runtime preference
  useEffect(() => {
    if (visible) {
      setMessage("");
      setTrunkBranch(defaultTrunk ?? branches[0] ?? "");
      setError(loadError ?? null);

      // Load saved runtime preference asynchronously
      void (async () => {
        try {
          const savedRuntime = await loadRuntimePreference(projectPath);
          if (savedRuntime) {
            const parsed = parseRuntimeModeAndHost(savedRuntime);
            setRuntimeMode(parsed.mode);
            setSshHost(parsed.host);
          } else {
            setRuntimeMode(RUNTIME_MODE.LOCAL);
            setSshHost("");
          }
        } catch (error) {
          console.error("Failed to load runtime preference:", error);
          setRuntimeMode(RUNTIME_MODE.LOCAL);
          setSshHost("");
        }
      })();
    }
  }, [visible, defaultTrunk, branches, loadError, projectPath]);

  const handleCancel = () => {
    setMessage("");
    setTrunkBranch(defaultTrunk ?? branches[0] ?? "");
    setRuntimeMode(RUNTIME_MODE.LOCAL);
    setSshHost("");
    setError(loadError ?? null);
    onClose();
  };

  const handleSend = async () => {
    const trimmedMessage = message.trim();
    if (trimmedMessage.length === 0) {
      setError("Message is required");
      return;
    }

    const normalizedTrunkBranch = trunkBranch.trim();
    if (normalizedTrunkBranch.length === 0) {
      setError("Trunk branch is required");
      return;
    }

    // Validate SSH host if SSH runtime selected
    if (runtimeMode === RUNTIME_MODE.SSH) {
      const trimmedHost = sshHost.trim();
      if (trimmedHost.length === 0) {
        setError("SSH host is required (e.g., hostname or user@host)");
        return;
      }
    }

    setIsLoading(true);
    setError(null);

    try {
      const runtime = buildRuntimeString(runtimeMode, sshHost);
      const metadata = await onSendFirstMessage(trimmedMessage, normalizedTrunkBranch, runtime);
      
      if (metadata) {
        // Reset form on success
        setMessage("");
        setTrunkBranch(defaultTrunk ?? branches[0] ?? "");
        setRuntimeMode(RUNTIME_MODE.LOCAL);
        setSshHost("");
        onClose();
      } else {
        setError("Failed to create workspace");
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "Failed to create workspace";
      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      onRequestClose={handleCancel}
      presentationStyle="pageSheet"
    >
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        style={{ flex: 1 }}
      >
        <View style={{ flex: 1, backgroundColor: theme.colors.background }}>
          {/* Header */}
          <View
            style={{
              flexDirection: "row",
              alignItems: "center",
              justifyContent: "space-between",
              paddingHorizontal: spacing.md,
              paddingTop: spacing.lg,
              paddingBottom: spacing.lg,
              borderBottomWidth: 1,
              borderBottomColor: theme.colors.borderSubtle,
            }}
          >
            <TouchableOpacity
              onPress={handleCancel}
              disabled={isLoading}
              style={{ paddingHorizontal: spacing.sm }}
            >
              <ThemedText style={{ fontSize: 17, color: theme.colors.accent }}>Cancel</ThemedText>
            </TouchableOpacity>
            <ThemedText style={{ fontSize: 17, fontWeight: "600" }}>Quick Start</ThemedText>
            <TouchableOpacity
              onPress={() => void handleSend()}
              disabled={isLoading || message.trim().length === 0 || trunkBranch.trim().length === 0}
              style={{ paddingHorizontal: spacing.sm }}
            >
              <ThemedText
                style={{
                  fontSize: 17,
                  color:
                    isLoading || message.trim().length === 0 || trunkBranch.trim().length === 0
                      ? theme.colors.foregroundMuted
                      : theme.colors.accent,
                  fontWeight: "600",
                }}
              >
                {isLoading ? "Creating..." : "Create"}
              </ThemedText>
            </TouchableOpacity>
          </View>

          {/* Project name */}
          <View
            style={{
              paddingHorizontal: spacing.lg,
              paddingVertical: spacing.md,
              backgroundColor: theme.colors.surfaceSunken,
            }}
          >
            <ThemedText style={{ fontSize: 13, opacity: 0.7, marginBottom: 2 }}>PROJECT</ThemedText>
            <ThemedText style={{ fontSize: 15 }}>{projectName}</ThemedText>
          </View>

          {/* Form */}
          <ScrollView
            style={{ flex: 1 }}
            contentContainerStyle={{
              padding: spacing.lg,
            }}
          >
            {/* Info text */}
            <View style={{ marginBottom: spacing.lg }}>
              <ThemedText
                style={{
                  fontSize: 14,
                  opacity: 0.8,
                  lineHeight: 20,
                }}
              >
                Describe what you want to build. A workspace will be created with an AI-generated
                name and branch. You can start working immediately.
              </ThemedText>
            </View>

            {/* First Message */}
            <View style={{ marginBottom: spacing.lg }}>
              <ThemedText
                style={{
                  fontSize: 12,
                  opacity: 0.6,
                  marginBottom: spacing.xs,
                  textTransform: "uppercase",
                  letterSpacing: 0.5,
                }}
              >
                What do you want to build?
              </ThemedText>
              <TextInput
                value={message}
                onChangeText={(value) => {
                  setMessage(value);
                  setError(null);
                }}
                placeholder="e.g., Add dark mode support to the app"
                placeholderTextColor={theme.colors.foregroundMuted}
                multiline
                numberOfLines={4}
                textAlignVertical="top"
                autoFocus
                editable={!isLoading}
                style={{
                  backgroundColor: theme.colors.background,
                  borderWidth: 1,
                  borderColor: theme.colors.border,
                  borderRadius: 8,
                  paddingHorizontal: spacing.md,
                  paddingVertical: spacing.md,
                  fontSize: 15,
                  color: theme.colors.foregroundPrimary,
                  minHeight: 100,
                }}
              />
              {error && (
                <ThemedText
                  style={{ fontSize: 13, color: theme.colors.danger, marginTop: spacing.xs }}
                >
                  {error}
                </ThemedText>
              )}
            </View>

            {/* Trunk Branch */}
            <View style={{ marginBottom: spacing.lg }}>
              <ThemedText
                style={{
                  fontSize: 12,
                  opacity: 0.6,
                  marginBottom: spacing.xs,
                  textTransform: "uppercase",
                  letterSpacing: 0.5,
                }}
              >
                Branch From
              </ThemedText>
              {hasBranches ? (
                <View
                  style={{
                    backgroundColor: theme.colors.background,
                    borderWidth: 1,
                    borderColor: theme.colors.border,
                    borderRadius: 8,
                    overflow: "hidden",
                  }}
                >
                  <Picker
                    selectedValue={trunkBranch}
                    onValueChange={(value) => setTrunkBranch(value)}
                    enabled={!isLoading}
                    style={{
                      color: theme.colors.foregroundPrimary,
                    }}
                    itemStyle={{
                      fontSize: 14,
                      color: theme.colors.foregroundPrimary,
                    }}
                  >
                    {branches.map((branch) => (
                      <Picker.Item key={branch} label={branch} value={branch} />
                    ))}
                  </Picker>
                </View>
              ) : (
                <>
                  <TextInput
                    value={trunkBranch}
                    onChangeText={setTrunkBranch}
                    placeholder="main"
                    placeholderTextColor={theme.colors.foregroundMuted}
                    autoCapitalize="none"
                    autoCorrect={false}
                    editable={!isLoading}
                    style={{
                      backgroundColor: theme.colors.background,
                      borderWidth: 1,
                      borderColor: theme.colors.border,
                      borderRadius: 8,
                      paddingHorizontal: spacing.md,
                      paddingVertical: 12,
                      fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
                      fontSize: 14,
                      color: theme.colors.foregroundPrimary,
                    }}
                  />
                  {loadError && (
                    <ThemedText
                      style={{
                        fontSize: 13,
                        color: theme.colors.danger,
                        marginTop: spacing.xs,
                      }}
                    >
                      No branches detected. Enter trunk branch manually.
                    </ThemedText>
                  )}
                </>
              )}
            </View>

            {/* Runtime Configuration */}
            <View style={{ marginBottom: spacing.lg }}>
              <ThemedText
                style={{
                  fontSize: 12,
                  opacity: 0.6,
                  marginBottom: spacing.xs,
                  textTransform: "uppercase",
                  letterSpacing: 0.5,
                }}
              >
                Runtime
              </ThemedText>
              <View
                style={{
                  backgroundColor: theme.colors.background,
                  borderWidth: 1,
                  borderColor: theme.colors.border,
                  borderRadius: 8,
                  overflow: "hidden",
                }}
              >
                <Picker
                  selectedValue={runtimeMode}
                  onValueChange={(value) => setRuntimeMode(value)}
                  enabled={!isLoading}
                  style={{
                    color: theme.colors.foregroundPrimary,
                  }}
                  itemStyle={{
                    fontSize: 14,
                    color: theme.colors.foregroundPrimary,
                  }}
                >
                  <Picker.Item label="Local" value={RUNTIME_MODE.LOCAL} />
                  <Picker.Item label="SSH Remote" value={RUNTIME_MODE.SSH} />
                </Picker>
              </View>

              {runtimeMode === RUNTIME_MODE.SSH && (
                <TextInput
                  value={sshHost}
                  onChangeText={setSshHost}
                  placeholder="user@host or hostname"
                  placeholderTextColor={theme.colors.foregroundMuted}
                  autoCapitalize="none"
                  autoCorrect={false}
                  editable={!isLoading}
                  style={{
                    backgroundColor: theme.colors.background,
                    borderWidth: 1,
                    borderColor: theme.colors.border,
                    borderRadius: 8,
                    paddingHorizontal: spacing.md,
                    paddingVertical: 12,
                    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
                    fontSize: 14,
                    color: theme.colors.foregroundPrimary,
                    marginTop: spacing.sm,
                  }}
                />
              )}

              <ThemedText
                style={{
                  fontSize: 12,
                  opacity: 0.6,
                  marginTop: spacing.xs,
                  lineHeight: 16,
                }}
              >
                Local: Creates git worktree in ~/.cmux/src
                {"\n"}
                SSH: Creates remote clone in ~/cmux on SSH host
              </ThemedText>
            </View>
          </ScrollView>
        </View>
      </KeyboardAvoidingView>
    </Modal>
  );
}
