/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/workspace-settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/workspace/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/workspace/[id]/review`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/workspace/[id]/settings`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/workspace-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/workspace/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/workspace/[id]/review`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/workspace/[id]/settings`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/workspace-settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/workspace-settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/workspace/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/workspace/${Router.SingleRoutePart<T>}/review${`?${string}` | `#${string}` | ''}` | `/workspace/${Router.SingleRoutePart<T>}/settings${`?${string}` | `#${string}` | ''}` | { pathname: `/workspace/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/workspace/[id]/review`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/workspace/[id]/settings`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
